name: windows

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - "go.*"
      - "**/*.go"
      - "Taskfile.yml"
      - ".github/workflows/windows.yml"
  pull_request:
    paths:
      - "go.*"
      - "**/*.go"
      - "Taskfile.yml"
      - ".github/workflows/windows.yml"

permissions:
  contents: read

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup-tparse
        run: go install github.com/mfridman/tparse@latest
      - run: task setup
      - name: test
        shell: bash
        run: ./scripts/test.sh test windows-latest
  build-pkgs:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v3
        with:
          path: dist/
          key: ${{ env.sha_short }}
          enableCrossOsArchive: true
      - run: task acceptance:windows:package
  install-pkgs:
    runs-on: ubuntu-latest
    needs: [build-pkgs]
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v3
        with:
          path: dist/
          key: ${{ env.sha_short }}
          enableCrossOsArchive: true
      - run: task acceptance:windows:install
